marketing_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: marketing_dw
      schema: analytics
      threads: 4